- type: job
  id: Psychologist
  name: job-name-psychologist
  description: job-description-psychologist
  playTimeTracker: JobPsychologist
  setPreference: false # Frontier
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: PsychologistGear
  icon: "JobIconPsychologist"
  supervisors: job-supervisors-hire # Frontier
  access:
  - Medical
  - Maintenance
  - Psychologist # DeltaV - Add Psychologist access
  extendedAccess:
  - Chemistry
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: PsychologistGear
  equipment:
    shoes: ClothingShoesLeather
    id: PsychologistPDA
    ears: ClothingHeadsetMedical
  storage:
    back:
    - RubberStampPsychologist
