- type: job
  id: Reporter
  name: job-name-reporter
  description: job-description-reporter
  playTimeTracker: JobReporter
  setPreference: true
  startingGear: ReporterGear
  icon: "JobIconReporter"
  supervisors: job-supervisors-hop
  access: # Frontier
  - Service # Frontier
  - Maintenance # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: ReporterGear
  equipment:
    shoes: ClothingShoesColorWhite
    # id: ReporterPDA
    # ears: ClothingHeadsetService
  #storage:
    #back:
    #- Stuff
