# Base prototypes can be found in \Resources\Prototypes\Recipes\Lathes\security.yml
#region Base
- type: latheRecipe
  id: BaseEmptyMagazineRecipe
  abstract: true
  categories:
  - NFMagazines
  completetime: 1

- type: latheRecipe
  id: BaseFilledMagazineRecipe
  parent: BaseEmptyMagazineRecipe
  abstract: true
  completetime: 2.5

#region Xbow Bolts
- type: latheRecipe # crossbow bolt
  id: CrossbowBolt
  parent: BaseAmmoRecipe
  result: CrossbowBolt
  materials:
    Steel: 20

- type: latheRecipe # crossbow bolt
  id: CrossbowBoltBroadhead
  parent: BaseAmmoRecipe
  result: CrossbowBoltBroadhead
  materials:
    Steel: 25

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponPistolPollock
  result: NFWeaponPistolPollock
  completetime: 3
  materials:
    Steel: 1000
    Plastic: 1200
    Plasteel: 1200

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: NFWeaponEnergyRifleCarbinePractice
  result: NFWeaponEnergyRifleCarbinePractice
  completetime: 6
  materials:
    Steel: 1800
    Glass: 400
    Plastic: 250

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: NFWeaponEnergyRifleCarbine
  result: NFWeaponEnergyRifleCarbine
  completetime: 6
  materials:
    Steel: 2000
    Glass: 800
    Plastic: 500

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: NFWeaponEnergyPistolDisablerPractice
  result: NFWeaponEnergyPistolDisablerPractice
  completetime: 4
  materials:
    Steel: 500
    Glass: 100
    Plastic: 200

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: NFWeaponEnergyPistolDisabler
  result: NFWeaponEnergyPistolDisabler
  completetime: 6
  materials:
    Steel: 500
    Glass: 200
    Plastic: 400

- type: latheRecipe
  parent: NFWeaponEnergyPistolDisabler # Frontier: WeaponDisabler<NFWeaponEnergyPistolDisabler
  id: NFWeaponEnergySubMachineGunDisabler # Frontier: WeaponDisablerSMG<NFWeaponEnergySubMachineGunDisabler
  result: NFWeaponEnergySubMachineGunDisabler # Frontier: WeaponDisablerSMG<NFWeaponEnergySubMachineGunDisabler
  materials:
    Steel: 1000
    Glass: 500
    Plastic: 500

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: NFWeaponEnergyPistolLaserAdvanced
  result: NFWeaponEnergyPistolLaserAdvanced
  materials:
    Steel: 1500
    Glass: 1000
    Gold: 850

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: NFWeaponEnergyRifleSniperCannon
  result: NFWeaponEnergyRifleSniperCannon
  materials:
    Steel: 1250
    Plastic: 750
    Gold: 500

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: NFWeaponEnergyPistolLaserSvalinn
  result: NFWeaponEnergyPistolLaserSvalinn
  materials:
    Steel: 2000
    Gold: 500

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: NFWeaponEnergyRifleSniperXrayCannon
  result: NFWeaponEnergyRifleSniperXrayCannon
  materials:
    Steel: 1500
    Glass: 500
    Plastic: 250
    Gold: 100

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: NFWeaponEnergyRifleTemperature
  result: NFWeaponEnergyRifleTemperature
  materials:
    Steel: 2000
    Glass: 500
    Plastic: 500
    Gold: 500

# region Grenades
- type: latheRecipe
  id: NFMagazineGrenadeEmpty # Frontier: add NF prefix
  result: NFMagazineGrenadeEmpty # Frontier: add NF prefix
  completetime: 3
  materials:
    Steel: 150
    Plastic: 50

- type: latheRecipe
  id: NFGrenadeEMP # Frontier: add NF prefix
  result: NFGrenadeEMP # Frontier: add NF prefix
  completetime: 3
  materials:
    Steel: 150
    Plastic: 100
    Glass: 20

- type: latheRecipe
  id: NFGrenadeBlast # Frontier: add NF prefix
  result: NFGrenadeBlast # Frontier: add NF prefix
  completetime: 3
  materials:
    Steel: 450
    Plastic: 300
    Gold: 150

- type: latheRecipe
  id: NFGrenadeFlash
  result: NFGrenadeFlash
  completetime: 3
  materials:
    Steel: 150
    Plastic: 100
    Glass: 20

# region Misc
- type: latheRecipe
  id: ClothingEyesHudNfsd
  parent: ClothingEyesHudSecurity
  result: ClothingEyesHudNfsd

- type: latheRecipe
  id: HoloprojectorNfsd
  parent: ClothingEyesHudSecurity
  result: HoloprojectorNfsdEmpty

# region Upstream Removed
- type: latheRecipe
  parent: Handcuffs
  id: NFHandcuffs

- type: latheRecipe
  parent: Zipties
  id: NFZipties

- type: latheRecipe
  parent: Stunbaton
  id: NFStunbaton

- type: latheRecipe
  parent: Truncheon
  id: NFTruncheon

- type: latheRecipe
  parent: CombatKnife
  id: NFCombatKnife

- type: latheRecipe
  parent: ClothingBackpackElectropack
  id: NFClothingBackpackElectropack

- type: latheRecipe
  parent: ForensicPad
  id: NFForensicPad

- type: latheRecipe
  parent: ClothingEyesHudSecurity
  id: NFClothingEyesHudSecurity

- type: latheRecipe
  parent: HoloprojectorSecurity
  id: NFHoloprojectorSecurityEmpty

- type: latheRecipe
  parent: RiotShield
  id: NFRiotShield

- type: latheRecipe
  parent: TelescopicShield
  id: NFTelescopicShield

- type: latheRecipe
  parent: Flash
  id: NFFlash

- type: latheRecipe
  id: NFTargetHuman
  result: TargetHuman

- type: latheRecipe
  parent: TargetClown
  id: NFTargetClown

- type: latheRecipe
  parent: TargetSyndicate
  id: NFTargetSyndicate

- type: latheRecipe
  id: NFPortableRecharger
  parent: PortableRecharger
